name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     
      - name: Checkout repository
        uses: actions/checkout@v3
     
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
     
      - name: Clear Gradle cache
        run: rm -rf ~/.gradle/caches/
      
      - name: Make Gradlew executable
        run: chmod +x gradlew
      
      - name: Build with Gradle
        run: ./gradlew build
      
      - name: Run tests
        run: ./gradlew test # Cucumber 테스트 대신 일반 JUnit 테스트 실행

      - name: Upload JUnit reports
        uses: actions/upload-artifact@v3
        with:
          name: junit-reports
          path: build/test-results/test/ # JUnit 테스트 결과 경로

      - name: Upload Cucumber reports (if applicable)
        if: success() && (steps.run-tests.outputs.cucumber == 'true')
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-reports
          path: build/reports/cucumber/ # Cucumber 리포트 경로

  codeql:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
