name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt' # 추가한 부분

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      env:
        APP_KEY: ${{ secrets.APP_KEY }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
      run: ./gradlew test

    - name: Analyze with CodeQL
      uses: github/codeql-action/analyze@v2
      with:
        category: 'security'
